version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: video_transcriptions
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: >
      bash -c "docker-entrypoint.sh postgres && psql -U user -d video_transcriptions -f /docker-entrypoint-initdb.d/init.sql"

volumes:
  postgres_data:
